# File is representation of development envrioment, generated by AI

# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages for MongoDB and wget for Go
RUN apt-get update && apt-get install -y gnupg wget software-properties-common

# MongoDB installation
RUN wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | apt-key add - \
    && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list \
    && apt-get update \
    && apt-get install -y mongodb-org=7.0.5

# Install Go 1.22.0
RUN wget https://go.dev/dl/go1.22.0.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz \
    && rm go1.22.0.linux-amd64.tar.gz

# Set PATH so that Go binaries are accessible
ENV PATH=$PATH:/usr/local/go/bin

# Verify installations
RUN mongod --version && go version

# Your container command (this can be modified to suit your needs)
CMD ["bash"]
